version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 propertyapp.wsgi
    # command: gunicorn --bind 0.0.0.0:$PORT propertyapp.wsgi
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

   